{
 "title": "Service Availability",
 "description": "Graphs on service availability",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 } },
  {
   "title": "Pool Provider Public Availability",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 7, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "appInsights": {
      "aggOptions": [
       "avg",
       "count"
      ],
      "aggregation": "avg",
      "alias": "{{dimensionvalue}}",
      "dimension": "availabilityResult/location",
      "dimensions": [
       "availabilityResult/name",
       "availabilityResult/location",
       "availabilityResult/success",
       "operation/name",
       "operation/synthetic",
       "operation/syntheticSource",
       "user/authenticated",
       "application/version",
       "client/type",
       "client/model",
       "client/os",
       "client/city",
       "client/stateOrProvince",
       "client/countryOrRegion",
       "client/browser",
       "cloud/roleName",
       "cloud/roleInstance",
       "customDimensions/FullTestResultAvailable",
       "customDimensions/WebtestArmResourceName",
       "customDimensions/SyntheticMonitorId",
       "customDimensions/WebtestLocationId",
       "customDimensions/SourceId"
      ],
      "metricName": "availabilityResults/availabilityPercentage",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": []
     }
    }
   ]
  },
  {
   "title": "Pool Provider Public Average Response Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 13, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "appInsights": {
      "aggOptions": [
       "avg",
       "min",
       "max",
       "sum",
       "count"
      ],
      "aggregation": "avg",
      "dimension": "none",
      "dimensions": [
       "request/source",
       "request/name",
       "request/urlHost",
       "request/urlPath",
       "request/success",
       "request/resultCode",
       "request/performanceBucket",
       "operation/name",
       "operation/synthetic",
       "operation/syntheticSource",
       "user/authenticated",
       "application/version",
       "client/type",
       "client/model",
       "client/os",
       "client/city",
       "client/stateOrProvince",
       "client/countryOrRegion",
       "client/browser",
       "cloud/roleName",
       "cloud/roleInstance",
       "customDimensions/_MS.ProcessedByMetricExtractors",
       "customDimensions/AspNetCoreEnvironment",
       "customDimensions/ConnectionId"
      ],
      "metricName": "requests/duration",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Average",
      "alias": "{{metric}}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimension": "None",
      "dimensionFilter": "*",
      "dimensions": [
       { "text": "None", "value": "None" },
       { "text": "Instance", "value": "Instance" }
      ],
      "metricDefinition": "Microsoft.Web/sites",
      "metricName": "AverageResponseTime",
      "metricNamespace": "Microsoft.Web/sites",
      "resourceGroup": "helixpoolprovider-dncengpublic-prod",
      "resourceName": "helixpoolprovider-dncengpublic-prod",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     }
    }
   ]
  },
  {
   "title": "Pool Provider Public Failed Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "appInsights": {
      "aggOptions": [ "sum" ],
      "aggregation": "sum",
      "alias": "{{dimensionvalue}}",
      "dimension": "request/resultCode",
      "dimensionFilter": "request/success eq false",
      "dimensions": [
       "request/source",
       "request/name",
       "request/urlHost",
       "request/urlPath",
       "request/success",
       "request/resultCode",
       "request/performanceBucket",
       "operation/name",
       "operation/synthetic",
       "operation/syntheticSource",
       "user/authenticated",
       "application/version",
       "client/type",
       "client/model",
       "client/os",
       "client/city",
       "client/stateOrProvince",
       "client/countryOrRegion",
       "client/browser",
       "cloud/roleName",
       "cloud/roleInstance",
       "customDimensions/_MS.ProcessedByMetricExtractors",
       "customDimensions/AspNetCoreEnvironment",
       "customDimensions/ConnectionId"
      ],
      "metricName": "requests/count",
      "rawQuery": true,
      "rawQueryString": "let r = requests | where $__timeFilter();\nlet f = toscalar(r | summarize min(timestamp));\nlet t = toscalar(r | summarize max(timestamp));\nr\n| where success == false and toint(resultCode) >= 500\n| make-series valueCount=count() default=0 on timestamp in range(f, t, 1m) by resultCode\n| mv-expand timestamp, valueCount\n| project timestamp=todatetime(timestamp), valueCount=toint(valueCount), resultCode",
      "segmentColumn": "resultCode",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": "valueCount"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": []
     }
    }
   ]
  },
  {
   "title": "Source Browser",
   "type": "graph",
   "description": "Availability tests for the site source.dot.net.",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "appInsights": {
      "aggOptions": [
       "avg",
       "count"
      ],
      "aggregation": "avg",
      "alias": "{{dimensionvalue}}",
      "dimension": "availabilityResult/location",
      "dimensionFilter": "availabilityResult/name eq 'source-dot-net'",
      "dimensions": [
       "availabilityResult/name",
       "availabilityResult/location",
       "availabilityResult/success",
       "operation/name",
       "operation/synthetic",
       "operation/syntheticSource",
       "user/authenticated",
       "application/version",
       "client/type",
       "client/model",
       "client/os",
       "client/city",
       "client/stateOrProvince",
       "client/countryOrRegion",
       "client/browser",
       "cloud/roleName",
       "cloud/roleInstance"
      ],
      "metricName": "availabilityResults/availabilityPercentage",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [ "Average" ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimension": "availabilityResult/name",
      "dimensionFilter": "Helix API",
      "dimensions": [
       { "text": "None", "value": "None" },
       { "text": "Test name", "value": "availabilityResult/name" },
       { "text": "Run location", "value": "availabilityResult/location" }
      ],
      "metricDefinition": "microsoft.insights/components",
      "metricName": "availabilityResults/availabilityPercentage",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "helixinfrarg",
      "resourceName": "helix-prod",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     }
    }
   ]
  },
  {
   "title": "Pool Provider Internal Availability",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 7, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "appInsights": {
      "aggOptions": [
       "avg",
       "count"
      ],
      "aggregation": "avg",
      "alias": "{{dimensionvalue}}",
      "dimension": "availabilityResult/location",
      "dimensions": [
       "availabilityResult/name",
       "availabilityResult/location",
       "availabilityResult/success",
       "operation/name",
       "operation/synthetic",
       "operation/syntheticSource",
       "user/authenticated",
       "application/version",
       "client/type",
       "client/model",
       "client/os",
       "client/city",
       "client/stateOrProvince",
       "client/countryOrRegion",
       "client/browser",
       "cloud/roleName",
       "cloud/roleInstance",
       "customDimensions/FullTestResultAvailable",
       "customDimensions/WebtestArmResourceName",
       "customDimensions/SyntheticMonitorId",
       "customDimensions/WebtestLocationId",
       "customDimensions/SourceId"
      ],
      "metricName": "availabilityResults/availabilityPercentage",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": []
     }
    }
   ]
  },
  {
   "title": "Pool Provider Internal Average Response Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 13, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "appInsights": {
      "aggOptions": [
       "avg",
       "min",
       "max",
       "sum",
       "count"
      ],
      "aggregation": "avg",
      "dimension": "none",
      "dimensions": [
       "request/source",
       "request/name",
       "request/urlHost",
       "request/urlPath",
       "request/success",
       "request/resultCode",
       "request/performanceBucket",
       "operation/name",
       "operation/synthetic",
       "operation/syntheticSource",
       "user/authenticated",
       "application/version",
       "client/type",
       "client/model",
       "client/os",
       "client/city",
       "client/stateOrProvince",
       "client/countryOrRegion",
       "client/browser",
       "cloud/roleName",
       "cloud/roleInstance",
       "customDimensions/_MS.ProcessedByMetricExtractors",
       "customDimensions/AspNetCoreEnvironment",
       "customDimensions/ConnectionId"
      ],
      "metricName": "requests/duration",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Average",
      "alias": "{{metric}}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimension": "None",
      "dimensionFilter": "*",
      "dimensions": [
       { "text": "None", "value": "None" },
       { "text": "Instance", "value": "Instance" }
      ],
      "metricDefinition": "Microsoft.Web/sites",
      "metricName": "AverageResponseTime",
      "metricNamespace": "Microsoft.Web/sites",
      "resourceGroup": "helixpoolprovider-dncenginternal-prod",
      "resourceName": "helixpoolprovider-dncenginternal-prod",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     }
    }
   ]
  },
  {
   "title": "Pool Provider Public Failed Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "appInsights": {
      "aggOptions": [ "sum" ],
      "aggregation": "sum",
      "alias": "{{dimensionvalue}}",
      "dimension": "request/resultCode",
      "dimensionFilter": "request/success eq false",
      "dimensions": [
       "request/source",
       "request/name",
       "request/urlHost",
       "request/urlPath",
       "request/success",
       "request/resultCode",
       "request/performanceBucket",
       "operation/name",
       "operation/synthetic",
       "operation/syntheticSource",
       "user/authenticated",
       "application/version",
       "client/type",
       "client/model",
       "client/os",
       "client/city",
       "client/stateOrProvince",
       "client/countryOrRegion",
       "client/browser",
       "cloud/roleName",
       "cloud/roleInstance",
       "customDimensions/_MS.ProcessedByMetricExtractors",
       "customDimensions/AspNetCoreEnvironment",
       "customDimensions/ConnectionId"
      ],
      "metricName": "requests/count",
      "rawQuery": true,
      "rawQueryString": "let r = requests | where $__timeFilter();\nlet f = toscalar(r | summarize min(timestamp));\nlet t = toscalar(r | summarize max(timestamp));\nr\n| where success == false and toint(resultCode) >= 500\n| make-series valueCount=count() default=0 on timestamp in range(f, t, 1m) by resultCode\n| mvexpand timestamp, valueCount\n| project timestamp=todatetime(timestamp), valueCount=toint(valueCount), resultCode",
      "segmentColumn": "resultCode",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": "valueCount"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": []
     }
    }
   ]
  },
  {
   "title": "Grafana",
   "type": "graph",
   "description": "Monitoring and alerting for the Grafana infrastructure is managed by Azure.",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "appInsights": {
      "aggOptions": [
       "avg",
       "count"
      ],
      "aggregation": "avg",
      "alias": "{{groupbyvalue}}",
      "dimension": "availabilityResult/location",
      "dimensionFilter": "availabilityResult/name eq 'Grafana Health'",
      "dimensions": [
       "availabilityResult/name",
       "availabilityResult/location",
       "availabilityResult/success",
       "operation/name",
       "operation/synthetic",
       "operation/syntheticSource",
       "user/authenticated",
       "application/version",
       "client/type",
       "client/model",
       "client/os",
       "client/city",
       "client/stateOrProvince",
       "client/countryOrRegion",
       "client/browser",
       "cloud/roleName",
       "cloud/roleInstance",
       "customDimensions/FullTestResultAvailable",
       "customDimensions/WebtestArmResourceName",
       "customDimensions/SyntheticMonitorId",
       "customDimensions/WebtestLocationId",
       "customDimensions/_MS.GSMv2",
       "customDimensions/SourceId"
      ],
      "metricName": "availabilityResults/availabilityPercentage",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": []
     }
    }
   ]
  },
  {
   "title": "Helix API",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 7, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "appInsights": {
      "aggOptions": [
       "avg",
       "count"
      ],
      "aggregation": "avg",
      "alias": "{{dimensionvalue}}",
      "dimension": "availabilityResult/location",
      "dimensionFilter": "availabilityResult/name eq 'Helix API'",
      "dimensions": [
       "availabilityResult/name",
       "availabilityResult/location",
       "availabilityResult/success",
       "operation/name",
       "operation/synthetic",
       "operation/syntheticSource",
       "user/authenticated",
       "application/version",
       "client/type",
       "client/model",
       "client/os",
       "client/city",
       "client/stateOrProvince",
       "client/countryOrRegion",
       "client/browser",
       "cloud/roleName",
       "cloud/roleInstance",
       "customDimensions/FullTestResultAvailable",
       "customDimensions/WebtestArmResourceName",
       "customDimensions/SyntheticMonitorId",
       "customDimensions/WebtestLocationId",
       "customDimensions/_MS.GSMv2",
       "customDimensions/SourceId"
      ],
      "metricName": "availabilityResults/availabilityPercentage",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "timeGrainCount": "",
      "timeGrainType": "auto",
      "timeGrainUnit": "",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\navailabilityResults                                                             //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "b165f541-bd03-4f8d-a509-8358194e2831"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "",
      "allowedTimeGrainsMs": [
       300000,
       3600000,
       86400000
      ],
      "dimension": "",
      "dimensionFilter": "*",
      "dimensions": [],
      "metricDefinition": "microsoft.insights/components",
      "metricName": "select",
      "metricNamespace": "availabilityResults",
      "resourceGroup": "helixinfrarg",
      "resourceName": "helix-prod",
      "timeGrain": "",
      "timeGrains": [],
      "top": "11"
     }
    }
   ]
  },
  {
   "title": "Helix Average Response Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 13, "y": 16 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "appInsights": {
      "aggOptions": [
       "avg",
       "min",
       "max",
       "sum",
       "count"
      ],
      "aggregation": "avg",
      "dimension": "none",
      "dimensions": [
       "request/source",
       "request/name",
       "request/urlHost",
       "request/urlPath",
       "request/success",
       "request/resultCode",
       "request/performanceBucket",
       "operation/name",
       "operation/synthetic",
       "operation/syntheticSource",
       "user/authenticated",
       "application/version",
       "client/type",
       "client/model",
       "client/os",
       "client/city",
       "client/stateOrProvince",
       "client/countryOrRegion",
       "client/browser",
       "cloud/roleName",
       "cloud/roleInstance",
       "customDimensions/AI internal",
       "customDimensions/webJobTypeName"
      ],
      "metricName": "requests/duration",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Average",
      "alias": "{{metric}}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimension": "None",
      "dimensionFilter": "*",
      "dimensions": [
       { "text": "None", "value": "None" },
       { "text": "Instance", "value": "Instance" }
      ],
      "metricDefinition": "Microsoft.Web/sites",
      "metricName": "AverageResponseTime",
      "metricNamespace": "Microsoft.Web/sites",
      "resourceGroup": "helixinfrarg",
      "resourceName": "helixview-prod",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     }
    }
   ]
  },
  {
   "title": "Helix Failed Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "appInsights": {
      "aggOptions": [ "sum" ],
      "aggregation": "sum",
      "alias": "{{dimensionvalue}}",
      "dimension": "request/resultCode",
      "dimensionFilter": "request/success eq false",
      "dimensions": [
       "request/source",
       "request/name",
       "request/urlHost",
       "request/urlPath",
       "request/success",
       "request/resultCode",
       "request/performanceBucket",
       "operation/name",
       "operation/synthetic",
       "operation/syntheticSource",
       "user/authenticated",
       "application/version",
       "client/type",
       "client/model",
       "client/os",
       "client/city",
       "client/stateOrProvince",
       "client/countryOrRegion",
       "client/browser",
       "cloud/roleName",
       "cloud/roleInstance",
       "customDimensions/_MS.ProcessedByMetricExtractors",
       "customDimensions/AspNetCoreEnvironment",
       "customDimensions/ConnectionId"
      ],
      "metricName": "requests/count",
      "rawQuery": true,
      "rawQueryString": "let r = requests | where $__timeFilter();\nlet f = toscalar(r | summarize min(timestamp));\nlet t = toscalar(r | summarize max(timestamp));\nr\n| where success == false and toint(resultCode) >= 500\n| make-series valueCount=count() default=0 on timestamp in range(f, t, 1m) by resultCode\n| mvexpand timestamp, valueCount\n| project timestamp=todatetime(timestamp), valueCount=toint(valueCount), resultCode",
      "segmentColumn": "resultCode",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": "valueCount"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": []
     }
    }
   ]
  },
  {
   "title": "Mission Control",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "appInsights": {
      "aggOptions": [
       "avg",
       "count"
      ],
      "aggregation": "avg",
      "alias": "{{dimensionvalue}}",
      "dimension": "availabilityResult/location",
      "dimensionFilter": "availabilityResult/name eq 'Mission Control'",
      "dimensions": [
       "availabilityResult/name",
       "availabilityResult/location",
       "availabilityResult/success",
       "operation/name",
       "operation/synthetic",
       "operation/syntheticSource",
       "user/authenticated",
       "application/version",
       "client/type",
       "client/model",
       "client/os",
       "client/city",
       "client/stateOrProvince",
       "client/countryOrRegion",
       "client/browser",
       "cloud/roleName",
       "cloud/roleInstance",
       "customDimensions/FullTestResultAvailable",
       "customDimensions/WebtestArmResourceName",
       "customDimensions/SyntheticMonitorId",
       "customDimensions/WebtestLocationId",
       "customDimensions/_MS.GSMv2",
       "customDimensions/SourceId"
      ],
      "metricName": "availabilityResults/availabilityPercentage",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "timeGrainCount": "",
      "timeGrainType": "auto",
      "timeGrainUnit": "",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\navailabilityResults                                                             //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "b165f541-bd03-4f8d-a509-8358194e2831"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "",
      "allowedTimeGrainsMs": [
       300000,
       3600000,
       86400000
      ],
      "dimension": "",
      "dimensionFilter": "*",
      "dimensions": [],
      "metricDefinition": "microsoft.insights/components",
      "metricName": "select",
      "metricNamespace": "availabilityResults",
      "resourceGroup": "helixinfrarg",
      "resourceName": "helix-prod",
      "timeGrain": "",
      "timeGrains": []
     }
    }
   ]
  },
  {
   "title": "Maestro / BarViz",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 7, "y": 24 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "appInsights": {
      "aggOptions": [
       "avg",
       "count"
      ],
      "aggregation": "avg",
      "alias": "{{dimensionvalue}}",
      "dimension": "availabilityResult/location",
      "dimensions": [
       "availabilityResult/name",
       "availabilityResult/location",
       "availabilityResult/success",
       "operation/name",
       "operation/synthetic",
       "operation/syntheticSource",
       "user/authenticated",
       "application/version",
       "client/type",
       "client/model",
       "client/os",
       "client/city",
       "client/stateOrProvince",
       "client/countryOrRegion",
       "client/browser",
       "cloud/roleName",
       "cloud/roleInstance",
       "customDimensions/FullTestResultAvailable",
       "customDimensions/WebtestArmResourceName",
       "customDimensions/SyntheticMonitorId",
       "customDimensions/WebtestLocationId",
       "customDimensions/SourceId"
      ],
      "metricName": "availabilityResults/availabilityPercentage",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [ "Average" ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimension": "availabilityResult/location",
      "dimensionFilter": "*",
      "dimensions": [
       { "text": "None", "value": "None" },
       { "text": "Test name", "value": "availabilityResult/name" },
       { "text": "Run location", "value": "availabilityResult/location" }
      ],
      "metricDefinition": "Microsoft.Insights/components",
      "metricName": "availabilityResults/availabilityPercentage",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "maestro-prod-cluster",
      "resourceName": "maestro-prod",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     }
    }
   ]
  },
  {
   "title": "Maestro Average Response Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 13, "y": 24 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "appInsights": {
      "aggOptions": [
       "avg",
       "min",
       "max",
       "sum",
       "count"
      ],
      "aggregation": "avg",
      "dimension": "none",
      "dimensions": [
       "request/source",
       "request/name",
       "request/urlHost",
       "request/urlPath",
       "request/success",
       "request/resultCode",
       "request/performanceBucket",
       "operation/name",
       "operation/synthetic",
       "operation/syntheticSource",
       "user/authenticated",
       "application/version",
       "client/type",
       "client/model",
       "client/os",
       "client/city",
       "client/stateOrProvince",
       "client/countryOrRegion",
       "client/browser",
       "cloud/roleName",
       "cloud/roleInstance",
       "customDimensions/AI internal",
       "customDimensions/webJobTypeName"
      ],
      "metricName": "requests/duration",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Average",
      "alias": "{{metric}}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimension": "None",
      "dimensionFilter": "*",
      "dimensions": [
       { "text": "None", "value": "None" },
       { "text": "Instance", "value": "Instance" }
      ],
      "metricDefinition": "Microsoft.Web/sites",
      "metricName": "AverageResponseTime",
      "metricNamespace": "Microsoft.Web/sites",
      "resourceGroup": "helixinfrarg",
      "resourceName": "helixview-prod",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     }
    }
   ]
  },
  {
   "title": "Maestro Failed Requests/Hour",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "appInsights": {
      "aggOptions": [ "sum" ],
      "aggregation": "sum",
      "alias": "{{dimensionvalue}}",
      "dimension": "request/resultCode",
      "dimensionFilter": "request/success eq false",
      "dimensions": [
       "request/source",
       "request/name",
       "request/urlHost",
       "request/urlPath",
       "request/success",
       "request/resultCode",
       "request/performanceBucket",
       "operation/name",
       "operation/synthetic",
       "operation/syntheticSource",
       "user/authenticated",
       "application/version",
       "client/type",
       "client/model",
       "client/os",
       "client/city",
       "client/stateOrProvince",
       "client/countryOrRegion",
       "client/browser",
       "cloud/roleName",
       "cloud/roleInstance",
       "customDimensions/_MS.ProcessedByMetricExtractors",
       "customDimensions/AspNetCoreEnvironment",
       "customDimensions/ConnectionId"
      ],
      "metricName": "requests/count",
      "rawQuery": true,
      "rawQueryString": "let r = requests | where $__timeFilter();\r\nlet f = toscalar(r | summarize min(timestamp));\r\nlet t = toscalar(r | summarize max(timestamp));\r\nlet span=(t - f)/60;\r\nlet interval=case(span >= 1d, bin(span, 1d), span >= 1h, bin(span, 1h), 15m);\r\nlet intervalHours = interval / 1h;\r\nr\r\n| where success == false and toint(resultCode) >= 500\r\n| make-series valueCount=count() default=0 on timestamp in range(f, t, interval) by resultCode\r\n| mv-expand timestamp, valueCount\r\n| project timestamp=todatetime(timestamp), failuresCount=todouble(valueCount)/intervalHours, resultCode",
      "segmentColumn": "resultCode",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": "failuresCount"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": []
     }
    }
   ]
  },
  {
   "title": "Pool Provider (Internal) AuthenticationException",
   "type": "graph",
   "description": "Sends an alert when the service tries to use an expired certificate ",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "appInsights": {
      "aggOptions": [ "sum" ],
      "aggregation": "sum",
      "alias": "Authorization Exception Count",
      "dimension": "exception/type",
      "dimensionFilter": "exception/type eq 'System.Security.Authentication.AuthenticationException'",
      "dimensions": [
       "exception/problemId",
       "exception/handledAt",
       "exception/type",
       "exception/assembly",
       "exception/method",
       "exception/severityLevel",
       "operation/name",
       "operation/synthetic",
       "operation/syntheticSource",
       "user/authenticated",
       "application/version",
       "client/type",
       "client/model",
       "client/os",
       "client/city",
       "client/stateOrProvince",
       "client/countryOrRegion",
       "client/browser",
       "cloud/roleName",
       "cloud/roleInstance",
       "customDimensions/ActionId",
       "customDimensions/CorrelationId",
       "customDimensions/AspNetCoreEnvironment",
       "customDimensions/RequestPath",
       "customDimensions/orchestrationId",
       "customDimensions/RequestId",
       "customDimensions/agentPool",
       "customDimensions/ActionName",
       "customDimensions/jobName",
       "customDimensions/agentId",
       "customDimensions/CategoryName",
       "customDimensions/{OriginalFormat}",
       "customDimensions/Exception"
      ],
      "metricName": "exceptions/count",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     }
    }
   ]
  },
  {
   "title": "Pool Provider (Public) AuthenticationException",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 7, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "appInsights": {
      "aggOptions": [ "sum" ],
      "aggregation": "sum",
      "alias": "Authorization Exception Count",
      "dimension": "exception/type",
      "dimensionFilter": "exception/type eq 'System.Security.Authentication.AuthenticationException'",
      "dimensions": [
       "exception/problemId",
       "exception/handledAt",
       "exception/type",
       "exception/assembly",
       "exception/method",
       "exception/severityLevel",
       "operation/name",
       "operation/synthetic",
       "operation/syntheticSource",
       "user/authenticated",
       "application/version",
       "client/type",
       "client/model",
       "client/os",
       "client/city",
       "client/stateOrProvince",
       "client/countryOrRegion",
       "client/browser",
       "cloud/roleName",
       "cloud/roleInstance",
       "customDimensions/ActionId",
       "customDimensions/CorrelationId",
       "customDimensions/AspNetCoreEnvironment",
       "customDimensions/RequestPath",
       "customDimensions/orchestrationId",
       "customDimensions/RequestId",
       "customDimensions/agentPool",
       "customDimensions/ActionName",
       "customDimensions/agentId",
       "customDimensions/jobName",
       "customDimensions/Machine_NumberOfProcessors",
       "customDimensions/RunningMode",
       "customDimensions/Machine_ComputeMode",
       "customDimensions/Machine_SKU",
       "customDimensions/ConnectionId",
       "customDimensions/CategoryName",
       "customDimensions/AgentVersion",
       "customDimensions/{OriginalFormat}",
       "customDimensions/Description",
       "customDimensions/message",
       "customDimensions/Exception",
       "customDimensions/TraceIdentifier",
       "customDimensions/Source",
       "customDimensions/handledAt",
       "customDimensions/Machine_EnvironmentType",
       "customDimensions/AgentSession",
       "customDimensions/MachineName"
      ],
      "metricName": "exceptions/count",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     }
    }
   ]
  },
  {
   "title": "DotNetEng Status Failed Requests/Hour",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 13, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": true,
      "rawQueryString": "let r = requests | where $__timeFilter();\r\nlet f = coalesce(toscalar(r | summarize min(timestamp)), ago(1d));\r\nlet t = coalesce(toscalar(r | summarize max(timestamp)), now());\nlet span=(t - f)/60;\r\nlet interval=case(span >= 1d, bin(span, 1d), span >= 1h, bin(span, 1h), 15m);\r\nlet intervalHours = interval / 1h;\r\nr\r\n| where success == false\n| make-series kind=nonempty valueCount=count() default=0 on timestamp in range(f, t, interval)\n| mv-expand timestamp, valueCount\r\n| project timestamp=todatetime(timestamp), failuresCount=todouble(valueCount)/intervalHours",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": "failuresCount"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     }
    }
   ]
  },
  {
   "title": "Helix AutoScaler Service Traces",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "appInsights": {
      "aggOptions": [ "sum" ],
      "aggregation": "sum",
      "alias": "{{groupbyvalue}}",
      "dimension": "cloud/roleName",
      "dimensionFilter": "cloud/roleName eq 'fabric:/CustomAutoScale/AutoScaleActorService' or cloud/roleName eq 'fabric:/CustomAutoScale/ProcessAutoScaleService'",
      "dimensions": [
       "trace/severityLevel",
       "operation/name",
       "operation/synthetic",
       "operation/syntheticSource",
       "application/version",
       "client/type",
       "client/model",
       "client/os",
       "client/city",
       "client/stateOrProvince",
       "client/countryOrRegion",
       "client/browser",
       "cloud/roleName",
       "cloud/roleInstance",
       "customDimensions/Scheme",
       "customDimensions/ServiceFabric.ApplicationName",
       "customDimensions/ServiceFabric.NodeName",
       "customDimensions/workitemId",
       "customDimensions/AspNetCoreEnvironment",
       "customDimensions/ServiceFabric.ApplicationTypeName",
       "customDimensions/ServiceFabric.InstanceId",
       "customDimensions/webJobTypeName",
       "customDimensions/ServiceFabric.ServiceName",
       "customDimensions/ServiceFabric.ServiceTypeName",
       "customDimensions/ParentId",
       "customDimensions/ServiceFabric.PartitionId",
       "customDimensions/messageId",
       "customDimensions/{OriginalFormat}",
       "customDimensions/needed",
       "customDimensions/shared",
       "customDimensions/count",
       "customDimensions/SpanId",
       "customDimensions/cloud_RoleName",
       "customDimensions/CategoryName",
       "customDimensions/RequestPath",
       "customDimensions/EventId",
       "customDimensions/ContentType",
       "customDimensions/ActionId",
       "customDimensions/RequestId",
       "customDimensions/TraceId",
       "customDimensions/heartbeatPageSize",
       "customDimensions/Protocol",
       "customDimensions/pingCount",
       "customDimensions/HttpMethod",
       "customDimensions/hasContinuation",
       "customDimensions/Method",
       "customDimensions/onPremisesCount",
       "customDimensions/Host",
       "customDimensions/heartbeatListSize",
       "customDimensions/Path",
       "customDimensions/ActionName",
       "customDimensions/EventName",
       "customDimensions/sub",
       "customDimensions/PageName",
       "customDimensions/ElapsedMilliseconds",
       "customDimensions/EndpointName",
       "customDimensions/ActionResult",
       "customDimensions/StatusCode",
       "customDimensions/RouteData",
       "customDimensions/ValidationState",
       "customDimensions/HandlerName",
       "customDimensions/scheduledMethod",
       "customDimensions/partitionCount",
       "customDimensions/webJobType",
       "customDimensions/nextFireTime",
       "customDimensions/partitionId",
       "customDimensions/MethodInfo",
       "customDimensions/cronDelay",
       "customDimensions/ServiceFabric.ReplicaId",
       "customDimensions/AssemblyName",
       "customDimensions/path",
       "customDimensions/partitionOffset",
       "customDimensions/region",
       "customDimensions/reserved",
       "customDimensions/Uri",
       "customDimensions/queue",
       "customDimensions/subscriptionId",
       "customDimensions/max",
       "customDimensions/q",
       "customDimensions/rewrittenUrl",
       "customDimensions/Controller",
       "customDimensions/Type",
       "customDimensions/jobId",
       "customDimensions/ContentLength",
       "customDimensions/queueId",
       "customDimensions/userName",
       "customDimensions/errorEventCount",
       "customDimensions/KeywordName",
       "customDimensions/Destination",
       "customDimensions/newCapacity",
       "customDimensions/queueName",
       "customDimensions/capacity",
       "customDimensions/containerName",
       "customDimensions/accountName",
       "customDimensions/expiration",
       "customDimensions/nodeName",
       "customDimensions/applicationTypeName",
       "customDimensions/replicaOrInstanceId",
       "customDimensions/RelatedActivityId",
       "customDimensions/serviceTypeName",
       "customDimensions/applicationName",
       "customDimensions/DeploymentName",
       "customDimensions/ProviderGuid",
       "customDimensions/ProviderName",
       "customDimensions/serviceName",
       "customDimensions/actorIdKind",
       "customDimensions/ActivityId",
       "customDimensions/actorType",
       "customDimensions/TaskName",
       "customDimensions/actorId",
       "customDimensions/Pid",
       "customDimensions/Tid",
       "customDimensions/orgCount",
       "customDimensions/teamCount",
       "customDimensions/subStatus",
       "customDimensions/service",
       "customDimensions/machineName",
       "customDimensions/serviceType",
       "customDimensions/upgradeType",
       "customDimensions/phase1DurationMs",
       "customDimensions/ServiceName",
       "customDimensions/applicationTypeVersion",
       "customDimensions/oldPrimaryNodeName",
       "customDimensions/newPrimaryNodeName",
       "customDimensions/slowCancellationTimeMillis",
       "customDimensions/newSecondaryNodeIds",
       "customDimensions/UnexpectedTermination",
       "customDimensions/QueryString",
       "customDimensions/totalDurationMs",
       "customDimensions/replicaId",
       "customDimensions/currentApplicationTypeVersion",
       "customDimensions/phase2DurationMs",
       "customDimensions/wasCanceled",
       "customDimensions/eventInstanceId",
       "customDimensions/OpcodeName",
       "customDimensions/eventName",
       "customDimensions/category",
       "customDimensions/ccEpoch_dataLossVersion",
       "customDimensions/rollingUpgradeMode",
       "customDimensions/ccEpoch_configVersion",
       "customDimensions/phase0DurationMs",
       "customDimensions/phase3DurationMs",
       "customDimensions/phase4DurationMs",
       "customDimensions/nodeInstance_id",
       "customDimensions/reconfigType",
       "customDimensions/activityId",
       "customDimensions/result",
       "customDimensions/targetReplicaId",
       "customDimensions/customeActorServiceType",
       "customDimensions/newSecondaryNodeNames",
       "customDimensions/SourceNode",
       "customDimensions/oldSecondaryNodeNames",
       "customDimensions/removeWhenExpired",
       "customDimensions/oldSecondaryNodeIds",
       "customDimensions/oldPrimaryNodeId",
       "customDimensions/newPrimaryNodeId",
       "customDimensions/instanceId",
       "customDimensions/upgradeDomainElapsedTimeInMs",
       "customDimensions/upgradeDomains",
       "customDimensions/upgradeState",
       "customDimensions/overallUpgradeElapsedTimeInMs",
       "customDimensions/TargetNode",
       "customDimensions/DecisionId",
       "customDimensions/ServicePackageActivationId",
       "customDimensions/MoveCost",
       "customDimensions/Service",
       "customDimensions/Action",
       "customDimensions/Phase",
       "customDimensions/failureAction",
       "customDimensions/actualCancellationTimeMillis",
       "customDimensions/sourceUtcTimestamp",
       "customDimensions/sequenceNumber",
       "customDimensions/TTL_timespan",
       "customDimensions/healthState",
       "customDimensions/description",
       "customDimensions/property",
       "customDimensions/sourceId",
       "customDimensions/EntryPointType",
       "customDimensions/HostId",
       "customDimensions/ProcessId",
       "customDimensions/ServicePackageName",
       "customDimensions/IsExclusive",
       "customDimensions/StartTime",
       "customDimensions/CodePackageName",
       "customDimensions/ExitCode",
       "customDimensions/ExeName",
       "customDimensions/Scope",
       "customDimensions/template",
       "customDimensions/0",
       "customDimensions/1",
       "customDimensions/commandType",
       "customDimensions/maxKey",
       "customDimensions/state",
       "customDimensions/PhysicalPath",
       "customDimensions/redirectedUrl",
       "customDimensions/elapsed",
       "customDimensions/commandTimeout",
       "customDimensions/commandText",
       "customDimensions/parameters",
       "customDimensions/VirtualPath",
       "customDimensions/contextType",
       "customDimensions/provider",
       "customDimensions/version",
       "customDimensions/options",
       "customDimensions/highKey",
       "customDimensions/minKey",
       "customDimensions/lowKey",
       "customDimensions/jobStartIdentifier",
       "customDimensions/resolvedQueueId",
       "customDimensions/reportedQueueId",
       "customDimensions/jobName",
       "customDimensions/replicaInstanceId",
       "customDimensions/AuthenticationScheme",
       "customDimensions/Schemes",
       "customDimensions/AuthorizationFilter",
       "customDimensions/name",
       "customDimensions/faultType",
       "customDimensions/nodeId",
       "customDimensions/cancelled",
       "customDimensions/currentClusterVersion",
       "customDimensions/scalesetMax",
       "customDimensions/nodeVersion",
       "customDimensions/configMax",
       "customDimensions/hostname",
       "customDimensions/deactivateIntent",
       "customDimensions/maxcapacity",
       "customDimensions/effectiveDeactivateIntent",
       "customDimensions/targetClusterVersion",
       "customDimensions/nodeInstance",
       "customDimensions/lastNodeDownAt",
       "customDimensions/lastNodeUpAt",
       "customDimensions/methodExecutionTimeTicks",
       "customDimensions/nodeInstanceId",
       "customDimensions/isSeedNode",
       "customDimensions/error",
       "customDimensions/ipAddressOrFQDN",
       "customDimensions/upgradeDomain",
       "customDimensions/faultDomain",
       "customDimensions/Reason",
       "customDimensions/batchIdsWithDeactivateIntent",
       "customDimensions/startTime",
       "customDimensions/batchId",
       "customDimensions/exception",
       "customDimensions/methodName",
       "customDimensions/methodSignature",
       "customDimensions/Message",
       "customDimensions/used",
       "customDimensions/surplus",
       "customDimensions/FailureMessage"
      ],
      "metricName": "traces/count",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     }
    }
   ]
  }
 ]
}